build.version: "5.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs"
  contactDetails:
    name: "Giri jyoti- Product Owner"
    email: "{cipher}965797b0ebc8847b319ce004a2e0f94e3f78c5a3c0b6283ba8896f599f6b03cf"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384

# 🛠️ ADD THIS BLOCK TO FILE BOTTOM TO ROUTE CONNECTIVITY TO PORT 8070
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
