spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jyotiranjan96/Jyotiranjan-java.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths:
            # Crucial: Ensure this matches the double 'configserver/configserver' layout we found
            - "section 1/v2-spring-cloud-config/configserver/configserver/src/main/resources/config"

server:
  port: 8071

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
